# Site settings
title: The DEV Liucoder.
SEOTitle: 刘玉峰的博客 | Liucoder Blog
header-img: 
email: liuyufengch@gmail.com
description: 
keyword: 
url: "https://liucoder.com"
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     cpudream
zhihu_username:     cpudream
github_username:    cpudream
twitter_username:   cpudream
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1



# Disqus settings
#disqus_username:

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 
ga_domain: 



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: 
sidebar-avatar: /img/avatar.jpg   # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

hotpages: [
    {
        title: "Android 高级混淆技巧总结    ",
        href:  "https://liucoder.com/2019/05/08/proguard/"
    }, {
        title: "Android Bitmap加载与压缩优化",
        href:  "https://liucoder.com/2018/04/01/bitmap-optimalize/"

    },{
        title: "NDK快速入门",
        href:  "https://liucoder.com/2017/06/27/ndk-guide/"
    },{
      title: "Windows下安装Jekyll",
      href:  "https://liucoder.com/2015/01/02/build-jekyll/"
    },{
        title: "如何自学 Android   ",
        href:  "http://gityuan.com/2016/04/24/how-to-study-android/"
    }
]

# Friends
friends: [
  {
        title: "当然我在扯淡",
        href: "http://www.yinwang.org/"
    },{
        title: "阮一峰的网络日志",
        href: "http://www.ruanyifeng.com/blog/"
    },{
        title: "Hux Blog",
        href: "https://huangxuan.me/"
    }
]
